server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /controversias-construccion-contratacion-publica {
    return 301 /resolucion-controversias-construccion-contratacion-publica/;
  }

  location = /controversias-construccion-contratacion-publica/ {
    return 301 /resolucion-controversias-construccion-contratacion-publica/;
  }

  location = /asesoria-legal-empresas {
    return 301 /asesoria-legal-empresa/;
  }

  location = /asesoria-legal-empresas/ {
    return 301 /asesoria-legal-empresa/;
  }

  location = /abogado-vina-del-mar {
    return 301 /;
  }

  location = /abogado-vina-del-mar/ {
    return 301 /;
  }

  location = /asesor-legal-vina-del-mar {
    return 301 /;
  }

  location = /asesor-legal-vina-del-mar/ {
    return 301 /;
  }

  location / {
    try_files $uri $uri/ $uri/index.html =404;
  }
}
